---
kind: pipeline
name: Full build and publish

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: owncloud-sdk

steps:
- name: increment-version
  pull: default
  image: node:11
  commands:
  - "yarn version --no-git-tag-version --new-version 1.0.0-${DRONE_BUILD_NUMBER}"
  when:
    event:
    - push

- name: build-docs
  pull: default
  image: node:11
  commands:
  - yarn install
  - yarn build:docs

- name: build-system
  pull: default
  image: node:11
  commands:
  - yarn install
  - yarn lint
  - yarn build:system

- name: prepare-test-config
  pull: default
  image: owncloud/ubuntu:16.04
  commands:
  - apt update
  - apt install gettext -y
  - "envsubst < tests/config/config.drone.json > tests/config/config.json"
  - cat tests/config/config.json
  environment:
    SUBFOLDER: "/"

- name: test
  pull: default
  image: owncloudci/chromium
  commands:
  - yarn test-drone

- name: publish-docs
  pull: default
  image: plugins/gh-pages:1
  settings:
    pages_directory: docs
  environment:
    GITHUB_PASSWORD:
      from_secret: github_password
    GITHUB_USERNAME:
      from_secret: github_username
  when:
    event:
    - push

- name: publish-system
  pull: default
  image: plugins/npm:1
  environment:
    NPM_EMAIL:
      from_secret: npm_email
    NPM_TOKEN:
      from_secret: npm_token
    NPM_USERNAME:
      from_secret: npm_username
  when:
    event:
    - push

services:

trigger:
  branch:
  - master

---
kind: pipeline
name: Test within a subfolder

platform:
  os: linux
  arch: amd64

workspace:
  base: /var/www/owncloud
  path: owncloud-sdk

steps:
- name: increment-version
  pull: default
  image: node:11
  commands:
  - "yarn version --no-git-tag-version --new-version 1.0.0-${DRONE_BUILD_NUMBER}"
  when:
    event:
    - push

- name: build-docs
  pull: default
  image: node:11
  commands:
  - yarn install
  - yarn build:docs

- name: build-system
  pull: default
  image: node:11
  commands:
  - yarn install
  - yarn lint
  - yarn build:system

- name: prepare-test-config
  pull: default
  image: owncloud/ubuntu:16.04
  commands:
  - apt update
  - apt install gettext -y
  - "envsubst < tests/config/config.drone.json > tests/config/config.json"
  - cat tests/config/config.json
  environment:
    SUBFOLDER: "/sub/"

- name: test
  pull: default
  image: owncloudci/chromium
  commands:
  - yarn test-drone

- name: publish-docs
  pull: default
  image: plugins/gh-pages:1
  settings:
    pages_directory: docs
  environment:
    GITHUB_PASSWORD:
      from_secret: github_password
    GITHUB_USERNAME:
      from_secret: github_username
  when:
    event:
    - push

- name: publish-system
  pull: default
  image: plugins/npm:1
  environment:
    NPM_EMAIL:
      from_secret: npm_email
    NPM_TOKEN:
      from_secret: npm_token
    NPM_USERNAME:
      from_secret: npm_username
  when:
    event:
    - push

services:

trigger:
  branch:
  - master


...
